destination: ./_site
auto: false
lsi: false
pygments: false
markdown: maruku
permalink: /:title.html
exclude: lib source Blog.sublime-project Blog.sublime-workspace rakefile.rb rakefile.sample.rb
current_theme: network

name: Tanner's Blog
description: The personal blog for Tanner Smith.
url: http://www.tannersmith.me

maruku:
  use_tex:    false
  use_divs:   false
  png_dir:    images/latex
  png_url:    /images/latex