destination: ./_site
lsi: false
pygments: false
markdown: maruku
permalink: /:title.html
exclude: [lib, originals, old_themes, rakefile.rb, rakefile.sample.rb]

name: Tanner's Blog
description: The personal blog for Tanner Smith.
url: http://www.tannersmith.me