destination: ./_site
permalink: /:year/:month/:day/:title/
exclude: [lib, originals, old_themes, rakefile.rb, rakefile.sample.rb, Makefile, Gemfile.lock]
include: [.htaccess]
url: http://tanner.github.io/Blog/
baseurl: ""
markdown: kramdown
collections:
- books

title: Tanner's Blog
description: The personal blog for Tanner Smith.
