destination: ./_site
auto: false
lsi: false
pygments: false
markdown: maruku
permalink: /:title.html
paginate: 1

maruku:
  use_tex:    false
  use_divs:   false
  png_dir:    images/latex
  png_url:    /images/latex