destination: ./_site
lsi: false
pygments: false
markdown: maruku
permalink: /:title.html
exclude: [lib source Blog.sublime-project Blog.sublime-workspace rakefile.rb rakefile.sample.rb]

name: Tanner's Blog
description: The personal blog for Tanner Smith.
url: http://www.tannersmith.me